### ISSUE TITLE
Set up backend of firebase so that class data can be fetched for viewing 

### ISSUE THREAD

**Issue by zsenzer** [cbubel/CISC475-Project#9]

**Comment by nlane** [comment]
Create schemas for semester, class, section, and student data.

  Student:
      - Name
      - UD id number
      - UD username / email
      - Graduate/Undergraduate
      - Schedule (3-tuples of start time, end time, and days)
      - Classes Taken/grades
      - Other info/tags
      - MAYBE graduation date? Or semester? (to be asked at next meeting)

  Class:
      - Title (course id)
      - Array of sections
      - Active/Inactive
      - Tags/other info

  Section:
      - Section id
      - Prof
      - Time/Day
      - Number of students in section
      - List of needed assignments (tuple of TA/LA, Undergrad/Grad)

   Semester:
       - Year/Spring vs Fall (i.e. 14F)
       - Final assignments (tuples of student ids and section ids)
